name: flutter_university_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/Ellipse 1.png
    - images/Banner Photo.jpg
    - images/Banner Shades.png
    - images/Back Button.png
    - images/Line 1.png
    - images/Google.png
    - images/Facebook.png
    - images/Twitter.png
  fonts:
    - family: Rochester
      fonts:
        - asset: fonts/Rochester-Regular.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Medium.ttf
